name: Self-hosted Runner Setup

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Download and configure runner
      uses: actions/runner@v2
      with:
        version: '2.277.1' # version of the runner to download
      env:
        RUNNER_NAME: my-runner # name of the runner
        RUNNER_TOKEN: ${{ secrets.RUNNER_TOKEN }} # access token for the runner
        REPO_URL: https://github.com/funmmer/GPT-QHU # URL of the repository
        ORG_RUNNER: false # set to true if the runner is for an organization repository
        LABELS: my-runner-label # label for the runner
