name: Python Workflow

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Python script in the background
      run: nohup python3 gpt.py > api.log 2>&1 &
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        TOKEN: ${{ secrets.mykey }}
        BRANCH: gh-pages
        FOLDER: .
        CLEAN: true
